import "./globals.css";
import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import React from "react";

const inter = Figtree({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props {
  children: React.ReactNode;
  auth: React.ReactNode;
}
export default function RootLayout({ children, auth }: Props) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        {auth}
      </body>
    </html>
  );
}
