const carKeys = [
  "ks_ferrari_f2004",
  "ks_praga_r1",
  "lotus_98t",
  "lotus_exos_125",
  "tatuusfa1",
];
const trackKeys = [
  "monaco_2017",
  "spa",
  "monza",
  "ks_silverstone-gp",
  "ks_silverstone-international",
  "ks_silverstone-national",
  "vir-full course",
  "vir-grand east course",
  "vir-grand west course",
  "vir-north course",
  "vir-patriot course",
  "vir-patriot reverse course",
  "vir-south course",
];

export const SAMPLE_EVENTS = [
  {
    name: "OWSR Community Race 1",
    game: "assetto-corsa",
    cars: ["ks_praga_r1"],
    image: "/images/sample/praga-silverstone.jpg",
    track: "silverstone-gp",
    date: "2024-07-15",
    startTime: "2024-07-15T18:00:00",
    eventType: "community",
    regOpen: "2024-07-01T00:00:00",
    regClose: "2024-07-15T17:30:00",
    maxParticipants: 20,
    dlcRequired: false,
    modsRequired: false,
    paidContentRequired: false,
    license: "R",
    fixedSetup: false,
    tags: ["community", "praga", "silverstone"],
  },
  {
    name: "Ferrari F2004 Challenge - Round 1",
    game: "assetto-corsa",
    cars: ["ks_ferrari_f2004"],
    image: "/images/sample/f2004spacard.jpg",
    track: "monza",
    date: "2024-07-22",
    startTime: "2024-07-22T18:00:00",
    regOpen: "2024-07-01T00:00:00",
    regClose: "2024-07-22T17:30:00",
    maxParticipants: 24,
    dlcRequired: true,
    modsRequired: false,
    paidContentRequired: false,
    license: "B",
    fixedSetup: false,
    tags: ["ferrari", "monza"],
    eventType: "community",
  },
  {
    name: "OWSR Community Race 2",
    game: "assetto-corsa",
    image: "/images/sample/exos.jpg",
    cars: ["lotus_exos_125"],
    track: "spa",
    date: "2024-07-29",
    startTime: "2024-07-28T18:00:00",
    regOpen: "2024-07-04T00:00:00",
    regClose: "2024-07-18T17:30:00",
    maxParticipants: 25,
    dlcRequired: false,
    modsRequired: false,
    paidContentRequired: false,
    fixedSetup: true,
    tags: ["community", "spa", "lotus"],
    eventType: "community",
    license: "R",
  },
  {
    name: "Historic F1 Series - Round 1",
    game: "assetto-corsa",
    cars: ["lotus_98t"],
    image: "/images/sample/lotuspa.jpg",
    track: "monza",
    date: "2024-07-05",
    startTime: "2024-07-05T18:00:00",
    regOpen: "2024-06-01T00:00:00",
    regClose: "2024-07-05T17:30:00",
    maxParticipants: 20,
    dlcRequired: false,
    modsRequired: false,
    paidContentRequired: false,
    fixedSetup: true,
    license: "C",
    tags: ["historic", "lotus", "monza"],
    eventType: "championship",
  },
  {
    name: "Formula Abarth League - Race 1",
    game: "assetto-corsa",
    image: "/images/sample/abarthseries.jpg",
    cars: ["tatuusfa1"],
    track: "vir-south course",
    date: "2024-07-12",
    startTime: "2024-07-12T18:00:00",
    regOpen: "2024-06-01T00:00:00",
    regClose: "2024-07-12T17:30:00",
    maxParticipants: 30,
    dlcRequired: false,
    modsRequired: true,
    paidContentRequired: false,
    license: "C",
    fixedSetup: true,
    tags: ["formula-abarth", "tatuus", "vir"],
    eventType: "league",
  },
  {
    name: "Weekly Hotlap Challenge",
    game: "assetto-corsa",
    cars: ["ks_praga_r1"],
    image: "/images/sample/praga-silverstone.jpg",
    track: "spa",
    date: "2024-07-01",
    startTime: "2024-07-01T00:00:00",
    regOpen: "2024-06-01T00:00:00",
    regClose: "2024-07-01T23:59:59",
    maxParticipants: -1,
    dlcRequired: false,
    modsRequired: false,
    paidContentRequired: false,
    fixedSetup: false,
    tags: ["hotlap", "praga", "spa"],
    eventType: "hotlap",
    license: "R",
  },
];
